name: LLM Ops Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        set -e

    - name: Linting
      run: |
        pylint model/llm_model.py
        set -e

    - name: Testing
      run: python -m unittest discover tests/

    - name: LLM Model Deployment
      run: python model/llm_model.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}             # Update with the right info
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     # Update with the right info
